### ISSUE TITLE
Offer a button on the learner dashboard to the user to kick off the process

### ISSUE THREAD

**Issue by Aldaviva** [Aldaviva/sans-aclp-security-training-defeat-device#3]
Currently, opening the learner dashboard will start opening and completing any incomplete required modules. It might be nice to only start doing this once the user clicks some sort of Begin button, so that a user can be mentally ready for the computer to take over their interactions, or if they want to use the page for anything else.

**Comment by Aldaviva** [comment]
The page is closed between modules, so how should we store the state that the user wants to defeat the modules across page loads? They might change their mind at some point.

Maybe a checkbox backed by `LocalStorage`.

**Comment by plluke** [comment]
Yes on localStorage. When enabled, the defeat process will continue within 2 seconds automatically (with a UI that allows the user to interrupt) every time the user is on the learner dashboard. If not enabled, the user is presented with UI that allows them to kick off the entire process.

The only slightly unclean part is that a user can close the whole thing out in the middle of a module, thereby leaving localStorage stuck in the enabled position. When the user returns to the learner dashboard he/she could arguably want to see UI to kick off the whole process again. Alternatively, one could see it as a "feature" that interrupted processes continue (with aforementioned 2 second escape interval) so I'm leaving the behavior as is.
